spring.application.name=digital
server.port=${PORT}
server.address=0.0.0.0
spring.config.import=optional:file:.env[.properties]
scheduler.round-robin.delay-seconds=${ROUND_ROBIN}
scheduler.round-robin.max-concurrent=${ROUND_ROBIN_MAX_CONCURRENT}
scheduler.plan.action=${PLAN_ACTION}
scheduler.interrogation.time=${INTERROGATION_NOTIFY}
scheduler.log.cleanup=${LOG_CLEANUP}
scheduler.qualification.analytics=${QUALIFICATION_ANALYTICS}
scheduler.task.cleanup=${TASK_CLEANUP}


app.frontend.url=${FRONTEND_URL}

spring.web.error.include-stacktrace=always
spring.web.error.include-message=always

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=${DRIVER_CLASS_NAME}

spring.datasource.fl.url=${SPRING_DATASOURCE_FL_URL}
spring.datasource.fl.username=${SPRING_DATASOURCE_FL_USERNAME}
spring.datasource.fl.password=${SPRING_DATASOURCE_FL_PASSWORD}
spring.datasource.fl.driver-class-name=${SPRING_DATASOURCE_FL_DRIVER_CLASS_NAME}


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

# C:\Program Files\Minio
# minio.exe server C:\minio-data --console-address ":9001"
minio.url= ${MINIO_URL}
minio.public.url=${MINIO_PUBLIC_URL}
minio.access.key= ${MINIO_ACCESS_KEY}
minio.secret.key= ${MINIO_SECRET_KEY}
minio.bucket.name=${MINIO_BUCKET_NAME}
minio.presigned.url.expiry.hours=${MINIO_PRESIGNED_URL_EXPIRY_HOURS}

spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DATABASE}

# docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:management
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.rabbitmq.mediator.queue=${RABBITMQ_MEDIATOR_QUEUE}
spring.rabbitmq.mediator.exchange=${RABBITMQ_MEDIATOR_EXCHANGE}
spring.rabbitmq.mediator.routing-key=${RABBITMQ_MEDIATOR_ROUTING_KEY}

spring.rabbitmq.mediator.result.queue=${RABBITMQ_MEDIATOR_RESULT_QUEUE}
spring.rabbitmq.mediator.result.exchange=${RABBITMQ_MEDIATOR_RESULT_EXCHANGE}
spring.rabbitmq.mediator.result.routing-key=${RABBITMQ_MEDIATOR_RESULT_ROUTING_KEY}
spring.rabbitmq.mediator.result.success.routing-key=${RABBITMQ_MEDIATOR_RESULT_SUCCESS_ROUTING_KEY}
spring.rabbitmq.mediator.result.failure.routing-key=${RABBITMQ_MEDIATOR_RESULT_FAILURE_ROUTING_KEY}

spring.rabbitmq.dlq.queue=${RABBITMQ_DLQ_QUEUE}
spring.rabbitmq.dlq.exchange=${RABBITMQ_DLQ_EXCHANGE}
spring.rabbitmq.dlq.routing-key=${RABBITMQ_DLQ_ROUTING_KEY}

spring.rabbitmq.inter.queue=${RABBITMQ_INTER_QUEUE}
spring.rabbitmq.inter.exchange=${RABBITMQ_INTER_EXCHANGE}
spring.rabbitmq.inter.routing-key=${RABBITMQ_INTER_ROUTING_KEY}

spring.rabbitmq.inter.result.queue=${RABBITMQ_INTER_RESULT_QUEUE}
spring.rabbitmq.inter.result.exchange=${RABBITMQ_INTER_RESULT_EXCHANGE}
spring.rabbitmq.inter.result.routing-key=${RABBITMQ_INTER_RESULT_ROUTING_KEY}

spring.rabbitmq.osmotr.queue=${RABBITMQ_OSMOTR_QUEUE}
spring.rabbitmq.osmotr.exchange=${RABBITMQ_OSMOTR_EXCHANGE}
spring.rabbitmq.osmotr.routing-key=${RABBITMQ_OSMOTR_ROUTING_KEY}

spring.rabbitmq.osmotr.result.queue=${RABBITMQ_OSMOTR_RESULT_QUEUE}
spring.rabbitmq.osmotr.result.exchange=${RABBITMQ_OSMOTR_RESULT_EXCHANGE}
spring.rabbitmq.osmotr.result.routing-key=${RABBITMQ_OSMOTR_RESULT_ROUTING_KEY}

spring.rabbitmq.report.queue=${RABBITMQ_REPORT_QUEUE}
spring.rabbitmq.report.exchange=${RABBITMQ_REPORT_EXCHANGE}
spring.rabbitmq.report.routing-key=${RABBITMQ_REPORT_ROUTING_KEY}

spring.rabbitmq.report.result.queue=${RABBITMQ_REPORT_RESULT_QUEUE}
spring.rabbitmq.report.result.exchange=${RABBITMQ_REPORT_RESULT_EXCHANGE}
spring.rabbitmq.report.result.routing-key=${RABBITMQ_REPORT_RESULT_ROUTING_KEY}

model.host=${MODEL_HOST}
qualification.port=${QUALIFICATION_PORT}
tree.port=${TREE_PORT}
index.port=${INDEX_PORT}
chat.port=${CHAT_PORT}
plan.port=${PLAN_PORT}
indictment.port=${INDICTMENT_PORT}
interrogation.port=${INTERROGATION_PORT}
figurant.port=${FIGURANT_PORT}
reformulate.port=${REFORMULATE_PORT}
osmotr.port=${OSMOTR_PORT}
qualification.analytics.port=${QUALIFICATION_ANALYTICS_PORT}


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-part-count=-1

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.leak-detection-threshold=20000

last.seen.ttl=${LAST_SEEN_TTL}
old.log.cleanup=${OLD_LOG_CLEANUP}
spring.mvc.async.request-timeout=600000

spring.mail.host=192.168.30.25
spring.mail.port=25
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

chat.typing.delay-ms=20

face.auth.threshold=0.5
face.auth.max-templates=5
face.auth.descriptor-length=128
face.auth.liveness-ttl-seconds=180
face.auth.liveness-token-ttl-minutes=5
face.auth.challenge-ttl-millis=120000

logging.level.org.springframework.web.socket.sockjs.transport.handler.DefaultSockJsService=ERROR
#logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
#logging.level.org.springframework.web=DEBUG