spring.application.name=digital
server.port=${PORT}
server.address=0.0.0.0
spring.config.import=optional:file:.env[.properties]
scheduler.round-robin.delay-seconds=${ROUND_ROBIN}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=${DRIVER_CLASS_NAME}

spring.datasource.fl.url=${SPRING_DATASOURCE_FL_URL}
spring.datasource.fl.username=${SPRING_DATASOURCE_FL_USERNAME}
spring.datasource.fl.password=${SPRING_DATASOURCE_FL_PASSWORD}
spring.datasource.fl.driver-class-name=${SPRING_DATASOURCE_FL_DRIVER_CLASS_NAME}


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# C:\Program Files\Minio
# minio.exe server C:\minio-data --console-address ":9001"
minio.url= ${MINIO_URL}
minio.public.url=${MINIO_PUBLIC_URL}
minio.access.key= ${MINIO_ACCESS_KEY}
minio.secret.key= ${MINIO_SECRET_KEY}
minio.bucket.name=${MINIO_BUCKET_NAME}
minio.presigned.url.expiry.hours=${MINIO_PRESIGNED_URL_EXPIRY_HOURS}

spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DATABASE}

# docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:management
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.rabbitmq.mediator.queue=${RABBITMQ_MEDIATOR_QUEUE}
spring.rabbitmq.mediator.exchange=${RABBITMQ_MEDIATOR_EXCHANGE}
spring.rabbitmq.mediator.routing-key=${RABBITMQ_MEDIATOR_ROUTING_KEY}

spring.rabbitmq.mediator.result.queue=${RABBITMQ_MEDIATOR_RESULT_QUEUE}
spring.rabbitmq.mediator.result.exchange=${RABBITMQ_MEDIATOR_RESULT_EXCHANGE}
spring.rabbitmq.mediator.result.routing-key=${RABBITMQ_MEDIATOR_RESULT_ROUTING_KEY}
spring.rabbitmq.mediator.result.success.routing-key=${RABBITMQ_MEDIATOR_RESULT_SUCCESS_ROUTING_KEY}
spring.rabbitmq.mediator.result.failure.routing-key=${RABBITMQ_MEDIATOR_RESULT_FAILURE_ROUTING_KEY}

spring.rabbitmq.dlq.queue=${RABBITMQ_DLQ_QUEUE}
spring.rabbitmq.dlq.exchange=${RABBITMQ_DLQ_EXCHANGE}
spring.rabbitmq.dlq.routing-key=${RABBITMQ_DLQ_ROUTING_KEY}

spring.rabbitmq.inter.queue=${RABBITMQ_INTER_QUEUE}
spring.rabbitmq.inter.exchange=${RABBITMQ_INTER_EXCHANGE}
spring.rabbitmq.inter.routing-key=${RABBITMQ_INTER_ROUTING_KEY}

spring.rabbitmq.inter.result.queue=${RABBITMQ_INTER_RESULT_QUEUE}
spring.rabbitmq.inter.result.exchange=${RABBITMQ_INTER_RESULT_EXCHANGE}
spring.rabbitmq.inter.result.routing-key=${RABBITMQ_INTER_RESULT_ROUTING_KEY}

qualification.model.host=${QUALIFICATION_MODEL_HOST}
qualification.model.port=${QUALIFICATION_MODEL_PORT}
index.control.port=${INDEX_CONTROL_PORT}
chat.model.port=${CHAT_MODEL_PORT}

indictment.model.host=${INDICTMENT_MODEL_HOST}
indictment.model.port=${INDICTMENT_MODEL_PORT}

interrogation.model.host=${INTERROGATION_MODEL_HOST}
interrogation.model.port=${INTERROGATION_MODEL_PORT}

plan.generator.host=${PLAN_GENERATOR_HOST}
plan.generator.port=${PLAN_GENERATOR_PORT}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-part-count=-1


spring.mvc.async.request-timeout=600000